---
language: go
go:
    - 1.5
    - 1.6
    - tip

services:
  - redis-server    

install:
    - go get -v -t ./...

before_script:
    # sleep a bit to allow things to get set up
    - sleep 10

script:
    - go test -v ./...

after_failure:
    - tail -n100 ./*.log